url: "https://ariannelafraise.github.io"
baseurl: "/portfolio"

permalink: pretty

collections:
  projects:
    output: true

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "article"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"
